name: cwas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - tqdm
  - glmnet
  - collections
  - matplotlib
  - rpy2
  - sklearn
  - pysam
  - tabix
  - pyyaml
  - python-dotenv
  - pytest
  - perl
  - perl-dbi
  - perl-dbd-mysql
  - perl-set-intervaltree
  - perl-bio-bigfile
  - perl-dbd-sqlite
  - perl-bio-db-hts
  - perl-bioperl
