name: cwas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl
  - perl-dbi
  - perl-dbd-mysql
  - perl-set-intervaltree
  - perl-bio-bigfile
  - perl-dbd-sqlite
  - perl-bio-db-hts
  - perl-bioperl
